//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Compra_DetalleCompra", "Compra", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra), "DetalleCompra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra), true)]
[assembly: EdmRelationshipAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Proveedor_Compra", "Proveedor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor), "Compra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra), true)]
[assembly: EdmRelationshipAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Producto_DetalleCompra", "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto), "DetalleCompra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra), true)]
[assembly: EdmRelationshipAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Producto_DetalleVenta", "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto), "DetalleVenta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta), true)]
[assembly: EdmRelationshipAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Cargo_Empleado", "Cargo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo), "Empleado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado), true)]
[assembly: EdmRelationshipAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "VentaSet_DetalleVenta", "VentaSet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet), "DetalleVenta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta), true)]
[assembly: EdmRelationshipAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Empleado_VentaSet", "Empleado", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado), "VentaSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet), true)]
[assembly: EdmRelationshipAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Venta_Cliente", "ClienteSet", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente), "VentaSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet), true)]

#endregion

namespace C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext usando la cadena de conexión encontrada en la sección 'C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext' del archivo de configuración de la aplicación.
        /// </summary>
        public C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext() : base("name=C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext", "C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext.
        /// </summary>
        public C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext(string connectionString) : base(connectionString, "C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext.
        /// </summary>
        public C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext(EntityConnection connection) : base(connection, "C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cargo> CargoSet
        {
            get
            {
                if ((_CargoSet == null))
                {
                    _CargoSet = base.CreateObjectSet<Cargo>("CargoSet");
                }
                return _CargoSet;
            }
        }
        private ObjectSet<Cargo> _CargoSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cliente> ClienteSet
        {
            get
            {
                if ((_ClienteSet == null))
                {
                    _ClienteSet = base.CreateObjectSet<Cliente>("ClienteSet");
                }
                return _ClienteSet;
            }
        }
        private ObjectSet<Cliente> _ClienteSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Compra> CompraSet
        {
            get
            {
                if ((_CompraSet == null))
                {
                    _CompraSet = base.CreateObjectSet<Compra>("CompraSet");
                }
                return _CompraSet;
            }
        }
        private ObjectSet<Compra> _CompraSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<DetalleCompra> DetalleCompraSet
        {
            get
            {
                if ((_DetalleCompraSet == null))
                {
                    _DetalleCompraSet = base.CreateObjectSet<DetalleCompra>("DetalleCompraSet");
                }
                return _DetalleCompraSet;
            }
        }
        private ObjectSet<DetalleCompra> _DetalleCompraSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<DetalleVenta> DetalleVentaSet
        {
            get
            {
                if ((_DetalleVentaSet == null))
                {
                    _DetalleVentaSet = base.CreateObjectSet<DetalleVenta>("DetalleVentaSet");
                }
                return _DetalleVentaSet;
            }
        }
        private ObjectSet<DetalleVenta> _DetalleVentaSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Empleado> EmpleadoSet
        {
            get
            {
                if ((_EmpleadoSet == null))
                {
                    _EmpleadoSet = base.CreateObjectSet<Empleado>("EmpleadoSet");
                }
                return _EmpleadoSet;
            }
        }
        private ObjectSet<Empleado> _EmpleadoSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Producto> ProductoSet
        {
            get
            {
                if ((_ProductoSet == null))
                {
                    _ProductoSet = base.CreateObjectSet<Producto>("ProductoSet");
                }
                return _ProductoSet;
            }
        }
        private ObjectSet<Producto> _ProductoSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Proveedor> ProveedorSet
        {
            get
            {
                if ((_ProveedorSet == null))
                {
                    _ProveedorSet = base.CreateObjectSet<Proveedor>("ProveedorSet");
                }
                return _ProveedorSet;
            }
        }
        private ObjectSet<Proveedor> _ProveedorSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<VentaSet> VentaSet
        {
            get
            {
                if ((_VentaSet == null))
                {
                    _VentaSet = base.CreateObjectSet<VentaSet>("VentaSet");
                }
                return _VentaSet;
            }
        }
        private ObjectSet<VentaSet> _VentaSet;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet CargoSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCargoSet(Cargo cargo)
        {
            base.AddObject("CargoSet", cargo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ClienteSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToClienteSet(Cliente cliente)
        {
            base.AddObject("ClienteSet", cliente);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet CompraSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCompraSet(Compra compra)
        {
            base.AddObject("CompraSet", compra);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DetalleCompraSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDetalleCompraSet(DetalleCompra detalleCompra)
        {
            base.AddObject("DetalleCompraSet", detalleCompra);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DetalleVentaSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDetalleVentaSet(DetalleVenta detalleVenta)
        {
            base.AddObject("DetalleVentaSet", detalleVenta);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet EmpleadoSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEmpleadoSet(Empleado empleado)
        {
            base.AddObject("EmpleadoSet", empleado);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ProductoSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProductoSet(Producto producto)
        {
            base.AddObject("ProductoSet", producto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ProveedorSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProveedorSet(Proveedor proveedor)
        {
            base.AddObject("ProveedorSet", proveedor);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet VentaSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVentaSet(VentaSet ventaSet)
        {
            base.AddObject("VentaSet", ventaSet);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", Name="Cargo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cargo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cargo.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="nombreCargo">Valor inicial de la propiedad NombreCargo.</param>
        /// <param name="descripcion">Valor inicial de la propiedad Descripcion.</param>
        /// <param name="sueldo">Valor inicial de la propiedad Sueldo.</param>
        public static Cargo CreateCargo(global::System.Int32 id, global::System.String nombreCargo, global::System.String descripcion, global::System.Double sueldo)
        {
            Cargo cargo = new Cargo();
            cargo.Id = id;
            cargo.NombreCargo = nombreCargo;
            cargo.Descripcion = descripcion;
            cargo.Sueldo = sueldo;
            return cargo;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreCargo
        {
            get
            {
                return _NombreCargo;
            }
            set
            {
                OnNombreCargoChanging(value);
                ReportPropertyChanging("NombreCargo");
                _NombreCargo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreCargo");
                OnNombreCargoChanged();
            }
        }
        private global::System.String _NombreCargo;
        partial void OnNombreCargoChanging(global::System.String value);
        partial void OnNombreCargoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Sueldo
        {
            get
            {
                return _Sueldo;
            }
            set
            {
                OnSueldoChanging(value);
                ReportPropertyChanging("Sueldo");
                _Sueldo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sueldo");
                OnSueldoChanged();
            }
        }
        private global::System.Double _Sueldo;
        partial void OnSueldoChanging(global::System.Double value);
        partial void OnSueldoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Cargo_Empleado", "Empleado")]
        public EntityCollection<Empleado> Empleado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Empleado>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Cargo_Empleado", "Empleado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Empleado>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Cargo_Empleado", "Empleado", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cliente.
        /// </summary>
        /// <param name="dNI">Valor inicial de la propiedad DNI.</param>
        /// <param name="apellido">Valor inicial de la propiedad Apellido.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="cUIL">Valor inicial de la propiedad CUIL.</param>
        /// <param name="direccion">Valor inicial de la propiedad Direccion.</param>
        /// <param name="telefono">Valor inicial de la propiedad Telefono.</param>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static Cliente CreateCliente(global::System.Int64 dNI, global::System.String apellido, global::System.String nombre, global::System.Int64 cUIL, global::System.String direccion, global::System.String telefono, global::System.Int32 id)
        {
            Cliente cliente = new Cliente();
            cliente.DNI = dNI;
            cliente.Apellido = apellido;
            cliente.Nombre = nombre;
            cliente.CUIL = cUIL;
            cliente.Direccion = direccion;
            cliente.Telefono = telefono;
            cliente.Id = id;
            return cliente;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DNI
        {
            get
            {
                return _DNI;
            }
            set
            {
                OnDNIChanging(value);
                ReportPropertyChanging("DNI");
                _DNI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DNI");
                OnDNIChanged();
            }
        }
        private global::System.Int64 _DNI;
        partial void OnDNIChanging(global::System.Int64 value);
        partial void OnDNIChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CUIL
        {
            get
            {
                return _CUIL;
            }
            set
            {
                OnCUILChanging(value);
                ReportPropertyChanging("CUIL");
                _CUIL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CUIL");
                OnCUILChanged();
            }
        }
        private global::System.Int64 _CUIL;
        partial void OnCUILChanging(global::System.Int64 value);
        partial void OnCUILChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Venta_Cliente", "VentaSet")]
        public EntityCollection<VentaSet> VentaSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VentaSet>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Venta_Cliente", "VentaSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VentaSet>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Venta_Cliente", "VentaSet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", Name="Compra")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Compra : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Compra.
        /// </summary>
        /// <param name="fecha">Valor inicial de la propiedad Fecha.</param>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="compra_Proveedor">Valor inicial de la propiedad Compra_Proveedor.</param>
        public static Compra CreateCompra(global::System.DateTime fecha, global::System.Int32 id, global::System.Int32 compra_Proveedor)
        {
            Compra compra = new Compra();
            compra.Fecha = fecha;
            compra.Id = id;
            compra.Compra_Proveedor = compra_Proveedor;
            return compra;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Compra_Proveedor
        {
            get
            {
                return _Compra_Proveedor;
            }
            set
            {
                OnCompra_ProveedorChanging(value);
                ReportPropertyChanging("Compra_Proveedor");
                _Compra_Proveedor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Compra_Proveedor");
                OnCompra_ProveedorChanged();
            }
        }
        private global::System.Int32 _Compra_Proveedor;
        partial void OnCompra_ProveedorChanging(global::System.Int32 value);
        partial void OnCompra_ProveedorChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Compra_DetalleCompra", "DetalleCompra")]
        public EntityCollection<DetalleCompra> DetalleCompra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleCompra>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Compra_DetalleCompra", "DetalleCompra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleCompra>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Compra_DetalleCompra", "DetalleCompra", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Proveedor_Compra", "Proveedor")]
        public Proveedor Proveedor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Proveedor>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Proveedor_Compra", "Proveedor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Proveedor>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Proveedor_Compra", "Proveedor").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Proveedor> ProveedorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Proveedor>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Proveedor_Compra", "Proveedor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Proveedor>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Proveedor_Compra", "Proveedor", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", Name="DetalleCompra")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DetalleCompra : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto DetalleCompra.
        /// </summary>
        /// <param name="cantidad">Valor inicial de la propiedad Cantidad.</param>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="detalleCompra_Producto">Valor inicial de la propiedad DetalleCompra_Producto.</param>
        /// <param name="compra_DetalleCompra">Valor inicial de la propiedad Compra_DetalleCompra.</param>
        public static DetalleCompra CreateDetalleCompra(global::System.Int32 cantidad, global::System.Int32 id, global::System.Int32 detalleCompra_Producto, global::System.Int32 compra_DetalleCompra)
        {
            DetalleCompra detalleCompra = new DetalleCompra();
            detalleCompra.Cantidad = cantidad;
            detalleCompra.Id = id;
            detalleCompra.DetalleCompra_Producto = detalleCompra_Producto;
            detalleCompra.Compra_DetalleCompra = compra_DetalleCompra;
            return detalleCompra;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private global::System.Int32 _Cantidad;
        partial void OnCantidadChanging(global::System.Int32 value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrecioUnitario
        {
            get
            {
                return _PrecioUnitario;
            }
            set
            {
                OnPrecioUnitarioChanging(value);
                ReportPropertyChanging("PrecioUnitario");
                _PrecioUnitario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioUnitario");
                OnPrecioUnitarioChanged();
            }
        }
        private Nullable<global::System.Decimal> _PrecioUnitario;
        partial void OnPrecioUnitarioChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecioUnitarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DetalleCompra_Producto
        {
            get
            {
                return _DetalleCompra_Producto;
            }
            set
            {
                OnDetalleCompra_ProductoChanging(value);
                ReportPropertyChanging("DetalleCompra_Producto");
                _DetalleCompra_Producto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DetalleCompra_Producto");
                OnDetalleCompra_ProductoChanged();
            }
        }
        private global::System.Int32 _DetalleCompra_Producto;
        partial void OnDetalleCompra_ProductoChanging(global::System.Int32 value);
        partial void OnDetalleCompra_ProductoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Compra_DetalleCompra
        {
            get
            {
                return _Compra_DetalleCompra;
            }
            set
            {
                OnCompra_DetalleCompraChanging(value);
                ReportPropertyChanging("Compra_DetalleCompra");
                _Compra_DetalleCompra = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Compra_DetalleCompra");
                OnCompra_DetalleCompraChanged();
            }
        }
        private global::System.Int32 _Compra_DetalleCompra;
        partial void OnCompra_DetalleCompraChanging(global::System.Int32 value);
        partial void OnCompra_DetalleCompraChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Producto_DetalleCompra", "Producto")]
        public Producto Producto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Producto_DetalleCompra", "Producto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Producto_DetalleCompra", "Producto").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Producto> ProductoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Producto_DetalleCompra", "Producto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Producto>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Producto_DetalleCompra", "Producto", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Compra_DetalleCompra", "Compra")]
        public Compra Compra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Compra_DetalleCompra", "Compra").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Compra_DetalleCompra", "Compra").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Compra> CompraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Compra_DetalleCompra", "Compra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Compra>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Compra_DetalleCompra", "Compra", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", Name="DetalleVenta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DetalleVenta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto DetalleVenta.
        /// </summary>
        /// <param name="cantidad">Valor inicial de la propiedad Cantidad.</param>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="detalleVenta_Producto">Valor inicial de la propiedad DetalleVenta_Producto.</param>
        /// <param name="venta_DetalleVenta">Valor inicial de la propiedad Venta_DetalleVenta.</param>
        public static DetalleVenta CreateDetalleVenta(global::System.Int32 cantidad, global::System.Int32 id, global::System.Int32 detalleVenta_Producto, global::System.Int32 venta_DetalleVenta)
        {
            DetalleVenta detalleVenta = new DetalleVenta();
            detalleVenta.Cantidad = cantidad;
            detalleVenta.Id = id;
            detalleVenta.DetalleVenta_Producto = detalleVenta_Producto;
            detalleVenta.Venta_DetalleVenta = venta_DetalleVenta;
            return detalleVenta;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrecioUnitario
        {
            get
            {
                return _PrecioUnitario;
            }
            set
            {
                OnPrecioUnitarioChanging(value);
                ReportPropertyChanging("PrecioUnitario");
                _PrecioUnitario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioUnitario");
                OnPrecioUnitarioChanged();
            }
        }
        private Nullable<global::System.Decimal> _PrecioUnitario;
        partial void OnPrecioUnitarioChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecioUnitarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private global::System.Int32 _Cantidad;
        partial void OnCantidadChanging(global::System.Int32 value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DetalleVenta_Producto
        {
            get
            {
                return _DetalleVenta_Producto;
            }
            set
            {
                OnDetalleVenta_ProductoChanging(value);
                ReportPropertyChanging("DetalleVenta_Producto");
                _DetalleVenta_Producto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DetalleVenta_Producto");
                OnDetalleVenta_ProductoChanged();
            }
        }
        private global::System.Int32 _DetalleVenta_Producto;
        partial void OnDetalleVenta_ProductoChanging(global::System.Int32 value);
        partial void OnDetalleVenta_ProductoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Venta_DetalleVenta
        {
            get
            {
                return _Venta_DetalleVenta;
            }
            set
            {
                OnVenta_DetalleVentaChanging(value);
                ReportPropertyChanging("Venta_DetalleVenta");
                _Venta_DetalleVenta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Venta_DetalleVenta");
                OnVenta_DetalleVentaChanged();
            }
        }
        private global::System.Int32 _Venta_DetalleVenta;
        partial void OnVenta_DetalleVentaChanging(global::System.Int32 value);
        partial void OnVenta_DetalleVentaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Producto_DetalleVenta", "Producto")]
        public Producto Producto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Producto_DetalleVenta", "Producto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Producto_DetalleVenta", "Producto").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Producto> ProductoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Producto_DetalleVenta", "Producto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Producto>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Producto_DetalleVenta", "Producto", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "VentaSet_DetalleVenta", "VentaSet")]
        public VentaSet VentaSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VentaSet>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.VentaSet_DetalleVenta", "VentaSet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VentaSet>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.VentaSet_DetalleVenta", "VentaSet").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VentaSet> VentaSetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VentaSet>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.VentaSet_DetalleVenta", "VentaSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VentaSet>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.VentaSet_DetalleVenta", "VentaSet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", Name="Empleado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Empleado : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Empleado.
        /// </summary>
        /// <param name="dNI">Valor inicial de la propiedad DNI.</param>
        /// <param name="apellido">Valor inicial de la propiedad Apellido.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="cUIL">Valor inicial de la propiedad CUIL.</param>
        /// <param name="direccion">Valor inicial de la propiedad Direccion.</param>
        /// <param name="telefono">Valor inicial de la propiedad Telefono.</param>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="empleado_Cargo">Valor inicial de la propiedad Empleado_Cargo.</param>
        public static Empleado CreateEmpleado(global::System.Int64 dNI, global::System.String apellido, global::System.String nombre, global::System.Int64 cUIL, global::System.String direccion, global::System.String telefono, global::System.Int32 id, global::System.Int32 empleado_Cargo)
        {
            Empleado empleado = new Empleado();
            empleado.DNI = dNI;
            empleado.Apellido = apellido;
            empleado.Nombre = nombre;
            empleado.CUIL = cUIL;
            empleado.Direccion = direccion;
            empleado.Telefono = telefono;
            empleado.Id = id;
            empleado.Empleado_Cargo = empleado_Cargo;
            return empleado;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DNI
        {
            get
            {
                return _DNI;
            }
            set
            {
                OnDNIChanging(value);
                ReportPropertyChanging("DNI");
                _DNI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DNI");
                OnDNIChanged();
            }
        }
        private global::System.Int64 _DNI;
        partial void OnDNIChanging(global::System.Int64 value);
        partial void OnDNIChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CUIL
        {
            get
            {
                return _CUIL;
            }
            set
            {
                OnCUILChanging(value);
                ReportPropertyChanging("CUIL");
                _CUIL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CUIL");
                OnCUILChanged();
            }
        }
        private global::System.Int64 _CUIL;
        partial void OnCUILChanging(global::System.Int64 value);
        partial void OnCUILChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Empleado_Cargo
        {
            get
            {
                return _Empleado_Cargo;
            }
            set
            {
                OnEmpleado_CargoChanging(value);
                ReportPropertyChanging("Empleado_Cargo");
                _Empleado_Cargo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Empleado_Cargo");
                OnEmpleado_CargoChanged();
            }
        }
        private global::System.Int32 _Empleado_Cargo;
        partial void OnEmpleado_CargoChanging(global::System.Int32 value);
        partial void OnEmpleado_CargoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Cargo_Empleado", "Cargo")]
        public Cargo Cargo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cargo>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Cargo_Empleado", "Cargo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cargo>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Cargo_Empleado", "Cargo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cargo> CargoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cargo>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Cargo_Empleado", "Cargo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cargo>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Cargo_Empleado", "Cargo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Empleado_VentaSet", "VentaSet")]
        public EntityCollection<VentaSet> VentaSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VentaSet>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Empleado_VentaSet", "VentaSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VentaSet>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Empleado_VentaSet", "VentaSet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", Name="Producto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Producto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Producto.
        /// </summary>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="descripcion">Valor inicial de la propiedad Descripcion.</param>
        /// <param name="precioCompra">Valor inicial de la propiedad PrecioCompra.</param>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static Producto CreateProducto(global::System.String nombre, global::System.String descripcion, global::System.Decimal precioCompra, global::System.Int32 id)
        {
            Producto producto = new Producto();
            producto.Nombre = nombre;
            producto.Descripcion = descripcion;
            producto.PrecioCompra = precioCompra;
            producto.Id = id;
            return producto;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PrecioCompra
        {
            get
            {
                return _PrecioCompra;
            }
            set
            {
                OnPrecioCompraChanging(value);
                ReportPropertyChanging("PrecioCompra");
                _PrecioCompra = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioCompra");
                OnPrecioCompraChanged();
            }
        }
        private global::System.Decimal _PrecioCompra;
        partial void OnPrecioCompraChanging(global::System.Decimal value);
        partial void OnPrecioCompraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Stock
        {
            get
            {
                return _Stock;
            }
            set
            {
                OnStockChanging(value);
                ReportPropertyChanging("Stock");
                _Stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stock");
                OnStockChanged();
            }
        }
        private Nullable<global::System.Int32> _Stock;
        partial void OnStockChanging(Nullable<global::System.Int32> value);
        partial void OnStockChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Producto_DetalleCompra", "DetalleCompra")]
        public EntityCollection<DetalleCompra> DetalleCompra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleCompra>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Producto_DetalleCompra", "DetalleCompra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleCompra>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Producto_DetalleCompra", "DetalleCompra", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Producto_DetalleVenta", "DetalleVenta")]
        public EntityCollection<DetalleVenta> DetalleVenta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleVenta>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Producto_DetalleVenta", "DetalleVenta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleVenta>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Producto_DetalleVenta", "DetalleVenta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", Name="Proveedor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Proveedor : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Proveedor.
        /// </summary>
        /// <param name="cUIT">Valor inicial de la propiedad CUIT.</param>
        /// <param name="razonSocial">Valor inicial de la propiedad RazonSocial.</param>
        /// <param name="direccion">Valor inicial de la propiedad Direccion.</param>
        /// <param name="telefono">Valor inicial de la propiedad Telefono.</param>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static Proveedor CreateProveedor(global::System.Int64 cUIT, global::System.String razonSocial, global::System.String direccion, global::System.String telefono, global::System.Int32 id)
        {
            Proveedor proveedor = new Proveedor();
            proveedor.CUIT = cUIT;
            proveedor.RazonSocial = razonSocial;
            proveedor.Direccion = direccion;
            proveedor.Telefono = telefono;
            proveedor.Id = id;
            return proveedor;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CUIT
        {
            get
            {
                return _CUIT;
            }
            set
            {
                OnCUITChanging(value);
                ReportPropertyChanging("CUIT");
                _CUIT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CUIT");
                OnCUITChanged();
            }
        }
        private global::System.Int64 _CUIT;
        partial void OnCUITChanging(global::System.Int64 value);
        partial void OnCUITChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RazonSocial
        {
            get
            {
                return _RazonSocial;
            }
            set
            {
                OnRazonSocialChanging(value);
                ReportPropertyChanging("RazonSocial");
                _RazonSocial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RazonSocial");
                OnRazonSocialChanged();
            }
        }
        private global::System.String _RazonSocial;
        partial void OnRazonSocialChanging(global::System.String value);
        partial void OnRazonSocialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Proveedor_Compra", "Compra")]
        public EntityCollection<Compra> Compra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Compra>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Proveedor_Compra", "Compra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Compra>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Proveedor_Compra", "Compra", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", Name="VentaSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VentaSet : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto VentaSet.
        /// </summary>
        /// <param name="fecha">Valor inicial de la propiedad Fecha.</param>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="venta_Empleado">Valor inicial de la propiedad Venta_Empleado.</param>
        public static VentaSet CreateVentaSet(global::System.DateTime fecha, global::System.Int32 id, global::System.Int32 venta_Empleado)
        {
            VentaSet ventaSet = new VentaSet();
            ventaSet.Fecha = fecha;
            ventaSet.Id = id;
            ventaSet.Venta_Empleado = venta_Empleado;
            return ventaSet;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Venta_Empleado
        {
            get
            {
                return _Venta_Empleado;
            }
            set
            {
                OnVenta_EmpleadoChanging(value);
                ReportPropertyChanging("Venta_Empleado");
                _Venta_Empleado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Venta_Empleado");
                OnVenta_EmpleadoChanged();
            }
        }
        private global::System.Int32 _Venta_Empleado;
        partial void OnVenta_EmpleadoChanging(global::System.Int32 value);
        partial void OnVenta_EmpleadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Venta_Cliente
        {
            get
            {
                return _Venta_Cliente;
            }
            set
            {
                OnVenta_ClienteChanging(value);
                ReportPropertyChanging("Venta_Cliente");
                _Venta_Cliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Venta_Cliente");
                OnVenta_ClienteChanged();
            }
        }
        private Nullable<global::System.Int32> _Venta_Cliente;
        partial void OnVenta_ClienteChanging(Nullable<global::System.Int32> value);
        partial void OnVenta_ClienteChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "VentaSet_DetalleVenta", "DetalleVenta")]
        public EntityCollection<DetalleVenta> DetalleVenta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleVenta>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.VentaSet_DetalleVenta", "DetalleVenta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleVenta>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.VentaSet_DetalleVenta", "DetalleVenta", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Empleado_VentaSet", "Empleado")]
        public Empleado Empleado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleado>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Empleado_VentaSet", "Empleado").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleado>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Empleado_VentaSet", "Empleado").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Empleado> EmpleadoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleado>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Empleado_VentaSet", "Empleado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Empleado>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Empleado_VentaSet", "Empleado", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", "Venta_Cliente", "ClienteSet")]
        public Cliente ClienteSetItem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Venta_Cliente", "ClienteSet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Venta_Cliente", "ClienteSet").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteSetItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Venta_Cliente", "ClienteSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Venta_Cliente", "ClienteSet", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
