//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    
    [global::System.ServiceModel.DomainServices.Hosting.EnableClientAccess()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDomainService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DomainService<global::ApplicationData.Implementation.ApplicationDataObjectContext>
    {
    
        public ApplicationDataDomainService() : base()
        {
        }
    
    #region Public Methods
    
    #region Queries
    #endregion
    
        [global::System.ServiceModel.DomainServices.Server.Invoke(HasSideEffects=false)]
        public int __GetEntitySetCanInformation(string entitySetName)
        {
            return base.GetEntitySetCanInformation(entitySetName);
        }
    
        [global::System.ServiceModel.DomainServices.Server.Invoke(HasSideEffects=false)]
        public bool __CanExecuteOperation(string operationName)
        {
            return base.CanExecuteOperation(operationName);
        }
    
    #endregion
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService()
        {
            return new global::LightSwitchApplication.DataWorkspace().ApplicationData;
        }
    
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::ApplicationData.Implementation.ApplicationDataObjectContext>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
    
            return base.CreateObject(type);
        }
    
        protected override global::ApplicationData.Implementation.ApplicationDataObjectContext CreateObjectContext()
        {
            return new global::ApplicationData.Implementation.ApplicationDataObjectContext(base.GetEntityConnectionString(
                "_IntrinsicData", 
                "res://*/ApplicationData.csdl|res://*/ApplicationData.ssdl|res://*/ApplicationData.msl",
                "System.Data.SqlClient"));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            return null;
        }
    
    #endregion
    
    }
    
    [global::System.ServiceModel.DomainServices.Hosting.EnableClientAccess()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DDomainService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DomainService<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext>
    {
    
        public C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DDomainService() : base()
        {
        }
    
    #region Public Methods
    
    #region Cargo
    
        public void InsertCargo(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo entity)
        {
            if (entity.EntityState != global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.ObjectStateManager.ChangeObjectState(entity, global::System.Data.EntityState.Added);
            }
            else
            {
                this.ObjectContext.CargoSet.AddObject(entity);
            }
        }
    
        public void UpdateCargo(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo currentEntity)
        {
            global::System.ServiceModel.DomainServices.EntityFramework.ObjectContextExtensions.AttachAsModified(this.ObjectContext.CargoSet, currentEntity, this.ChangeSet.GetOriginal(currentEntity));
        }
    
        public void DeleteCargo(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo entity)
        {
            if (entity.EntityState == global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.CargoSet.Attach(entity);
            }
    
            this.DeleteEntity(entity);
        }
    #endregion
    
    #region Cliente
    
        public void InsertCliente(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente entity)
        {
            if (entity.EntityState != global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.ObjectStateManager.ChangeObjectState(entity, global::System.Data.EntityState.Added);
            }
            else
            {
                this.ObjectContext.ClienteSet.AddObject(entity);
            }
        }
    
        public void UpdateCliente(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente currentEntity)
        {
            global::System.ServiceModel.DomainServices.EntityFramework.ObjectContextExtensions.AttachAsModified(this.ObjectContext.ClienteSet, currentEntity, this.ChangeSet.GetOriginal(currentEntity));
        }
    
        public void DeleteCliente(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente entity)
        {
            if (entity.EntityState == global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.ClienteSet.Attach(entity);
            }
    
            this.DeleteEntity(entity);
        }
    #endregion
    
    #region Compra
    
        public void InsertCompra(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra entity)
        {
            if (entity.EntityState != global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.ObjectStateManager.ChangeObjectState(entity, global::System.Data.EntityState.Added);
            }
            else
            {
                this.ObjectContext.CompraSet.AddObject(entity);
            }
        }
    
        public void UpdateCompra(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra currentEntity)
        {
            global::System.ServiceModel.DomainServices.EntityFramework.ObjectContextExtensions.AttachAsModified(this.ObjectContext.CompraSet, currentEntity, this.ChangeSet.GetOriginal(currentEntity));
        }
    
        public void DeleteCompra(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra entity)
        {
            if (entity.EntityState == global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.CompraSet.Attach(entity);
            }
    
            this.DeleteEntity(entity);
        }
    #endregion
    
    #region DetalleCompra
    
        public void InsertDetalleCompra(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra entity)
        {
            if (entity.EntityState != global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.ObjectStateManager.ChangeObjectState(entity, global::System.Data.EntityState.Added);
            }
            else
            {
                this.ObjectContext.DetalleCompraSet.AddObject(entity);
            }
        }
    
        public void UpdateDetalleCompra(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra currentEntity)
        {
            global::System.ServiceModel.DomainServices.EntityFramework.ObjectContextExtensions.AttachAsModified(this.ObjectContext.DetalleCompraSet, currentEntity, this.ChangeSet.GetOriginal(currentEntity));
        }
    
        public void DeleteDetalleCompra(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra entity)
        {
            if (entity.EntityState == global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.DetalleCompraSet.Attach(entity);
            }
    
            this.DeleteEntity(entity);
        }
    #endregion
    
    #region DetalleVenta
    
        public void InsertDetalleVenta(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta entity)
        {
            if (entity.EntityState != global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.ObjectStateManager.ChangeObjectState(entity, global::System.Data.EntityState.Added);
            }
            else
            {
                this.ObjectContext.DetalleVentaSet.AddObject(entity);
            }
        }
    
        public void UpdateDetalleVenta(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta currentEntity)
        {
            global::System.ServiceModel.DomainServices.EntityFramework.ObjectContextExtensions.AttachAsModified(this.ObjectContext.DetalleVentaSet, currentEntity, this.ChangeSet.GetOriginal(currentEntity));
        }
    
        public void DeleteDetalleVenta(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta entity)
        {
            if (entity.EntityState == global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.DetalleVentaSet.Attach(entity);
            }
    
            this.DeleteEntity(entity);
        }
    #endregion
    
    #region Empleado
    
        public void InsertEmpleado(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado entity)
        {
            if (entity.EntityState != global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.ObjectStateManager.ChangeObjectState(entity, global::System.Data.EntityState.Added);
            }
            else
            {
                this.ObjectContext.EmpleadoSet.AddObject(entity);
            }
        }
    
        public void UpdateEmpleado(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado currentEntity)
        {
            global::System.ServiceModel.DomainServices.EntityFramework.ObjectContextExtensions.AttachAsModified(this.ObjectContext.EmpleadoSet, currentEntity, this.ChangeSet.GetOriginal(currentEntity));
        }
    
        public void DeleteEmpleado(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado entity)
        {
            if (entity.EntityState == global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.EmpleadoSet.Attach(entity);
            }
    
            this.DeleteEntity(entity);
        }
    #endregion
    
    #region Producto
    
        public void InsertProducto(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto entity)
        {
            if (entity.EntityState != global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.ObjectStateManager.ChangeObjectState(entity, global::System.Data.EntityState.Added);
            }
            else
            {
                this.ObjectContext.ProductoSet.AddObject(entity);
            }
        }
    
        public void UpdateProducto(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto currentEntity)
        {
            global::System.ServiceModel.DomainServices.EntityFramework.ObjectContextExtensions.AttachAsModified(this.ObjectContext.ProductoSet, currentEntity, this.ChangeSet.GetOriginal(currentEntity));
        }
    
        public void DeleteProducto(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto entity)
        {
            if (entity.EntityState == global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.ProductoSet.Attach(entity);
            }
    
            this.DeleteEntity(entity);
        }
    #endregion
    
    #region Proveedor
    
        public void InsertProveedor(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor entity)
        {
            if (entity.EntityState != global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.ObjectStateManager.ChangeObjectState(entity, global::System.Data.EntityState.Added);
            }
            else
            {
                this.ObjectContext.ProveedorSet.AddObject(entity);
            }
        }
    
        public void UpdateProveedor(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor currentEntity)
        {
            global::System.ServiceModel.DomainServices.EntityFramework.ObjectContextExtensions.AttachAsModified(this.ObjectContext.ProveedorSet, currentEntity, this.ChangeSet.GetOriginal(currentEntity));
        }
    
        public void DeleteProveedor(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor entity)
        {
            if (entity.EntityState == global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.ProveedorSet.Attach(entity);
            }
    
            this.DeleteEntity(entity);
        }
    #endregion
    
    #region VentaSet
    
        public void InsertVentaSet(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet entity)
        {
            if (entity.EntityState != global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.ObjectStateManager.ChangeObjectState(entity, global::System.Data.EntityState.Added);
            }
            else
            {
                this.ObjectContext.VentaSet.AddObject(entity);
            }
        }
    
        public void UpdateVentaSet(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet currentEntity)
        {
            global::System.ServiceModel.DomainServices.EntityFramework.ObjectContextExtensions.AttachAsModified(this.ObjectContext.VentaSet, currentEntity, this.ChangeSet.GetOriginal(currentEntity));
        }
    
        public void DeleteVentaSet(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet entity)
        {
            if (entity.EntityState == global::System.Data.EntityState.Detached)
            {
                this.ObjectContext.VentaSet.Attach(entity);
            }
    
            this.DeleteEntity(entity);
        }
    #endregion
    
    #region Queries
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo> CargoSet_Single(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo>("CargoSet_Single", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo> CargoSet_SingleOrDefault(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo>("CargoSet_SingleOrDefault", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo> CargoSet_All(string frameworkOperators)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo>("CargoSet_All", frameworkOperators);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente> ClienteSet_Single(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente>("ClienteSet_Single", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente> ClienteSet_SingleOrDefault(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente>("ClienteSet_SingleOrDefault", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente> ClienteSet_All(string frameworkOperators)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente>("ClienteSet_All", frameworkOperators);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra> CompraSet_Single(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra>("CompraSet_Single", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra> CompraSet_SingleOrDefault(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra>("CompraSet_SingleOrDefault", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra> CompraSet_All(string frameworkOperators)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra>("CompraSet_All", frameworkOperators);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra> DetalleCompraSet_Single(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra>("DetalleCompraSet_Single", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra> DetalleCompraSet_SingleOrDefault(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra>("DetalleCompraSet_SingleOrDefault", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra> DetalleCompraSet_All(string frameworkOperators)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra>("DetalleCompraSet_All", frameworkOperators);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta> DetalleVentaSet_Single(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta>("DetalleVentaSet_Single", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta> DetalleVentaSet_SingleOrDefault(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta>("DetalleVentaSet_SingleOrDefault", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta> DetalleVentaSet_All(string frameworkOperators)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta>("DetalleVentaSet_All", frameworkOperators);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado> EmpleadoSet_Single(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado>("EmpleadoSet_Single", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado> EmpleadoSet_SingleOrDefault(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado>("EmpleadoSet_SingleOrDefault", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado> EmpleadoSet_All(string frameworkOperators)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado>("EmpleadoSet_All", frameworkOperators);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto> ProductoSet_Single(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto>("ProductoSet_Single", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto> ProductoSet_SingleOrDefault(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto>("ProductoSet_SingleOrDefault", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto> ProductoSet_All(string frameworkOperators)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto>("ProductoSet_All", frameworkOperators);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor> ProveedorSet_Single(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor>("ProveedorSet_Single", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor> ProveedorSet_SingleOrDefault(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor>("ProveedorSet_SingleOrDefault", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor> ProveedorSet_All(string frameworkOperators)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor>("ProveedorSet_All", frameworkOperators);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet> VentaSet_Single(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet>("VentaSet_Single", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet> VentaSet_SingleOrDefault(string frameworkOperators, global::System.Nullable<int> Id)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet>("VentaSet_SingleOrDefault", frameworkOperators, Id);
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet> VentaSet_All(string frameworkOperators)
        {
            return this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet>("VentaSet_All", frameworkOperators);
        }
    
    #endregion
    
        [global::System.ServiceModel.DomainServices.Server.Invoke(HasSideEffects=false)]
        public int __GetEntitySetCanInformation(string entitySetName)
        {
            return base.GetEntitySetCanInformation(entitySetName);
        }
    
        [global::System.ServiceModel.DomainServices.Server.Invoke(HasSideEffects=false)]
        public bool __CanExecuteOperation(string operationName)
        {
            return base.CanExecuteOperation(operationName);
        }
    
    #endregion
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService()
        {
            return new global::LightSwitchApplication.DataWorkspace().C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D;
        }
    
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext>
    {
        public C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo> CargoSet_Single(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo>("CargoSet_All"),
                (c) => (Id.HasValue && (c.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo> CargoSet_SingleOrDefault(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo>("CargoSet_All"),
                (c) => (Id.HasValue && (c.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo> CargoSet_All()
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo> query;
            query = base.CreateQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo>("[CargoSet]").AsQueryable();
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente> ClienteSet_Single(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente>("ClienteSet_All"),
                (c) => (Id.HasValue && (c.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente> ClienteSet_SingleOrDefault(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente>("ClienteSet_All"),
                (c) => (Id.HasValue && (c.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente> ClienteSet_All()
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente> query;
            query = base.CreateQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente>("[ClienteSet]").AsQueryable();
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra> CompraSet_Single(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra>("CompraSet_All"),
                (c) => (Id.HasValue && (c.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra> CompraSet_SingleOrDefault(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra>("CompraSet_All"),
                (c) => (Id.HasValue && (c.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra> CompraSet_All()
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra> query;
            query = base.CreateQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra>("[CompraSet]").AsQueryable();
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra> DetalleCompraSet_Single(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra>("DetalleCompraSet_All"),
                (d) => (Id.HasValue && (d.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra> DetalleCompraSet_SingleOrDefault(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra>("DetalleCompraSet_All"),
                (d) => (Id.HasValue && (d.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra> DetalleCompraSet_All()
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra> query;
            query = base.CreateQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra>("[DetalleCompraSet]").AsQueryable();
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta> DetalleVentaSet_Single(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta>("DetalleVentaSet_All"),
                (d) => (Id.HasValue && (d.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta> DetalleVentaSet_SingleOrDefault(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta>("DetalleVentaSet_All"),
                (d) => (Id.HasValue && (d.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta> DetalleVentaSet_All()
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta> query;
            query = base.CreateQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta>("[DetalleVentaSet]").AsQueryable();
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado> EmpleadoSet_Single(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado>("EmpleadoSet_All"),
                (e) => (Id.HasValue && (e.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado> EmpleadoSet_SingleOrDefault(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado>("EmpleadoSet_All"),
                (e) => (Id.HasValue && (e.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado> EmpleadoSet_All()
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado> query;
            query = base.CreateQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado>("[EmpleadoSet]").AsQueryable();
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto> ProductoSet_Single(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto>("ProductoSet_All"),
                (p) => (Id.HasValue && (p.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto> ProductoSet_SingleOrDefault(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto>("ProductoSet_All"),
                (p) => (Id.HasValue && (p.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto> ProductoSet_All()
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto> query;
            query = base.CreateQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto>("[ProductoSet]").AsQueryable();
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor> ProveedorSet_Single(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor>("ProveedorSet_All"),
                (p) => (Id.HasValue && (p.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor> ProveedorSet_SingleOrDefault(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor>("ProveedorSet_All"),
                (p) => (Id.HasValue && (p.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor> ProveedorSet_All()
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor> query;
            query = base.CreateQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor>("[ProveedorSet]").AsQueryable();
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet> VentaSet_Single(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet>("VentaSet_All"),
                (v) => (Id.HasValue && (v.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet> VentaSet_SingleOrDefault(global::System.Nullable<int> Id)
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet>("VentaSet_All"),
                (v) => (Id.HasValue && (v.Id == Id)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet> VentaSet_All()
        {
            global::System.Linq.IQueryable<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet> query;
            query = base.CreateQuery<global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet>("[VentaSet]").AsQueryable();
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo();
            }
            if (type == typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente();
            }
            if (type == typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra();
            }
            if (type == typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra();
            }
            if (type == typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta();
            }
            if (type == typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado();
            }
            if (type == typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto();
            }
            if (type == typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor();
            }
            if (type == typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext CreateObjectContext()
        {
            return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DObjectContext(base.GetEntityConnectionString(
                "C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D", 
                "res://*/C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.csdl|res://*/C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.ssdl|res://*/C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.msl",
                "System.Data.SqlClient"));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Cargo))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Cliente))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Compra))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DetalleCompra))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DetalleVenta))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Empleado))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Producto))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Proveedor))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.VentaSet))
            {
                return new global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            if (dataServiceType == typeof(global::LightSwitchApplication.C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D))
            {
                return new global::LightSwitchApplication.C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D))
            {
                return new global::LightSwitchApplication.Implementation.C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_DServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Cargo) == definitionType)
            {
                return typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo);
            }
            if (typeof(global::LightSwitchApplication.Cliente) == definitionType)
            {
                return typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente);
            }
            if (typeof(global::LightSwitchApplication.Compra) == definitionType)
            {
                return typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra);
            }
            if (typeof(global::LightSwitchApplication.DetalleCompra) == definitionType)
            {
                return typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra);
            }
            if (typeof(global::LightSwitchApplication.DetalleVenta) == definitionType)
            {
                return typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta);
            }
            if (typeof(global::LightSwitchApplication.Empleado) == definitionType)
            {
                return typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado);
            }
            if (typeof(global::LightSwitchApplication.Producto) == definitionType)
            {
                return typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto);
            }
            if (typeof(global::LightSwitchApplication.Proveedor) == definitionType)
            {
                return typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor);
            }
            if (typeof(global::LightSwitchApplication.VentaSet) == definitionType)
            {
                return typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet);
            }
            return null;
        }
    }
}

namespace ApplicationData.Implementation
{

}

namespace C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation
{

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Cargo :
        global::LightSwitchApplication.Cargo.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Cargo.DetailsClass.IImplementation.Empleado
        {
            get
            {
                return this.Empleado;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Cliente :
        global::LightSwitchApplication.Cliente.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Cliente.DetailsClass.IImplementation.VentaSet
        {
            get
            {
                return this.VentaSet;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.ComponentModel.DataAnnotations.MetadataType(typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra.Metadata))]
    public partial class Compra :
        global::LightSwitchApplication.Compra.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Compra.DetailsClass.IImplementation.DetalleCompra
        {
            get
            {
                return this.DetalleCompra;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Compra.DetailsClass.IImplementation.Proveedor
        {
            get
            {
                return this.Proveedor;
            }
            set
            {
                this.Proveedor = (global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Proveedor");
                }
            }
        }
        
        partial void OnCompra_ProveedorChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Proveedor");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
        
        internal class Metadata
        {
            [global::System.ServiceModel.DomainServices.Server.Include]
            public global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Proveedor Proveedor { get; set; }
        
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.ComponentModel.DataAnnotations.MetadataType(typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleCompra.Metadata))]
    public partial class DetalleCompra :
        global::LightSwitchApplication.DetalleCompra.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DetalleCompra.DetailsClass.IImplementation.Producto
        {
            get
            {
                return this.Producto;
            }
            set
            {
                this.Producto = (global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Producto");
                }
            }
        }
        
        partial void OnDetalleCompra_ProductoChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Producto");
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DetalleCompra.DetailsClass.IImplementation.Compra
        {
            get
            {
                return this.Compra;
            }
            set
            {
                this.Compra = (global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Compra");
                }
            }
        }
        
        partial void OnCompra_DetalleCompraChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Compra");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
        
        internal class Metadata
        {
            [global::System.ServiceModel.DomainServices.Server.Include]
            public global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto Producto { get; set; }
        
            [global::System.ServiceModel.DomainServices.Server.Include]
            public global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Compra Compra { get; set; }
        
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.ComponentModel.DataAnnotations.MetadataType(typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.DetalleVenta.Metadata))]
    public partial class DetalleVenta :
        global::LightSwitchApplication.DetalleVenta.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DetalleVenta.DetailsClass.IImplementation.Producto
        {
            get
            {
                return this.Producto;
            }
            set
            {
                this.Producto = (global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Producto");
                }
            }
        }
        
        partial void OnDetalleVenta_ProductoChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Producto");
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DetalleVenta.DetailsClass.IImplementation.VentaSet
        {
            get
            {
                return this.VentaSet;
            }
            set
            {
                this.VentaSet = (global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("VentaSet");
                }
            }
        }
        
        partial void OnVenta_DetalleVentaChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("VentaSet");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
        
        internal class Metadata
        {
            [global::System.ServiceModel.DomainServices.Server.Include]
            public global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Producto Producto { get; set; }
        
            [global::System.ServiceModel.DomainServices.Server.Include]
            public global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet VentaSet { get; set; }
        
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.ComponentModel.DataAnnotations.MetadataType(typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado.Metadata))]
    public partial class Empleado :
        global::LightSwitchApplication.Empleado.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Empleado.DetailsClass.IImplementation.Cargo
        {
            get
            {
                return this.Cargo;
            }
            set
            {
                this.Cargo = (global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        partial void OnEmpleado_CargoChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Cargo");
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Empleado.DetailsClass.IImplementation.VentaSet
        {
            get
            {
                return this.VentaSet;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
        
        internal class Metadata
        {
            [global::System.ServiceModel.DomainServices.Server.Include]
            public global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cargo Cargo { get; set; }
        
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Producto :
        global::LightSwitchApplication.Producto.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Producto.DetailsClass.IImplementation.DetalleCompra
        {
            get
            {
                return this.DetalleCompra;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Producto.DetailsClass.IImplementation.DetalleVenta
        {
            get
            {
                return this.DetalleVenta;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Proveedor :
        global::LightSwitchApplication.Proveedor.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Proveedor.DetailsClass.IImplementation.Compra
        {
            get
            {
                return this.Compra;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.ComponentModel.DataAnnotations.MetadataType(typeof(global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.VentaSet.Metadata))]
    public partial class VentaSet :
        global::LightSwitchApplication.VentaSet.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.VentaSet.DetailsClass.IImplementation.DetalleVenta
        {
            get
            {
                return this.DetalleVenta;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.VentaSet.DetailsClass.IImplementation.Empleado
        {
            get
            {
                return this.Empleado;
            }
            set
            {
                this.Empleado = (global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        partial void OnVenta_EmpleadoChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Empleado");
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.VentaSet.DetailsClass.IImplementation.ClienteSetItem
        {
            get
            {
                return this.ClienteSetItem;
            }
            set
            {
                this.ClienteSetItem = (global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ClienteSetItem");
                }
            }
        }
        
        partial void OnVenta_ClienteChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ClienteSetItem");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
        
        internal class Metadata
        {
            [global::System.ServiceModel.DomainServices.Server.Include]
            public global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Empleado Empleado { get; set; }
        
            [global::System.ServiceModel.DomainServices.Server.Include]
            public global::C__USERS_JULIETA_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_AACD_D.Implementation.Cliente ClienteSetItem { get; set; }
        
        }
    }
    
}

