

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No hay ninguna descripción modelada
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class DetalleVenta : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Inicializa una nueva instancia de la entidad DetalleVenta.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DetalleVenta()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DetalleVenta(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DetalleVenta> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.DetalleVenta.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DetalleVenta_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DetalleVenta_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> PrecioUnitario
        {
            get
            {
                return global::LightSwitchApplication.DetalleVenta.DetailsClass.GetValue(this, global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.PrecioUnitario);
            }
            set
            {
                global::LightSwitchApplication.DetalleVenta.DetailsClass.SetValue(this, global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.PrecioUnitario, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PrecioUnitario_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PrecioUnitario_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PrecioUnitario_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Cantidad
        {
            get
            {
                return global::LightSwitchApplication.DetalleVenta.DetailsClass.GetValue(this, global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.Cantidad);
            }
            set
            {
                global::LightSwitchApplication.DetalleVenta.DetailsClass.SetValue(this, global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.Cantidad, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cantidad_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cantidad_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cantidad_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Subtotal
        {
            get
            {
                return global::LightSwitchApplication.DetalleVenta.DetailsClass.GetValue(this, global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.Subtotal);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subtotal_Compute(ref decimal result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subtotal_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.DetalleVenta.DetailsClass.GetValue(this, global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Producto Producto
        {
            get
            {
                return global::LightSwitchApplication.DetalleVenta.DetailsClass.GetValue(this, global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.Producto);
            }
            set
            {
                global::LightSwitchApplication.DetalleVenta.DetailsClass.SetValue(this, global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.Producto, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Producto_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Producto_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Producto_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.VentaSet VentaSet
        {
            get
            {
                return global::LightSwitchApplication.DetalleVenta.DetailsClass.GetValue(this, global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.VentaSet);
            }
            set
            {
                global::LightSwitchApplication.DetalleVenta.DetailsClass.SetValue(this, global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.VentaSet, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VentaSet_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VentaSet_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VentaSet_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.DetalleVenta,
                global::LightSwitchApplication.DetalleVenta.DetailsClass,
                global::LightSwitchApplication.DetalleVenta.DetailsClass.IImplementation,
                global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.PrecioUnitario;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass>.Entry
                __DetalleVentaEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass>.Entry(
                    global::LightSwitchApplication.DetalleVenta.DetailsClass.__DetalleVenta_CreateNew,
                    global::LightSwitchApplication.DetalleVenta.DetailsClass.__DetalleVenta_Created,
                    global::LightSwitchApplication.DetalleVenta.DetailsClass.__DetalleVenta_AllowSaveWithErrors);
            private static global::LightSwitchApplication.DetalleVenta __DetalleVenta_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DetalleVenta> es)
            {
                return new global::LightSwitchApplication.DetalleVenta(es);
            }
            private static void __DetalleVenta_Created(global::LightSwitchApplication.DetalleVenta e)
            {
                e.DetalleVenta_Created();
            }
            private static bool __DetalleVenta_AllowSaveWithErrors(global::LightSwitchApplication.DetalleVenta e)
            {
                bool result = false;
                e.DetalleVenta_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::System.Nullable<decimal>> PrecioUnitario
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.PrecioUnitario) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, int> Cantidad
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.Cantidad) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, decimal> Subtotal
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.Subtotal) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::LightSwitchApplication.Producto> Producto
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.Producto) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::LightSwitchApplication.Producto>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::LightSwitchApplication.VentaSet> VentaSet
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.VentaSet) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::LightSwitchApplication.VentaSet>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.Nullable<decimal> PrecioUnitario { get; set; }
                new int Cantidad { get; set; }
                new int Id { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Producto { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation VentaSet { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::System.Nullable<decimal>>.Entry
                    PrecioUnitario = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "PrecioUnitario",
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._PrecioUnitario_Stub,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._PrecioUnitario_ComputeIsReadOnly,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._PrecioUnitario_Validate,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._PrecioUnitario_GetImplementationValue,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._PrecioUnitario_SetImplementationValue,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._PrecioUnitario_OnValueChanged);
                private static void _PrecioUnitario_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DetalleVenta.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.DetalleVenta.DetailsClass d, object sf)
                {
                    c(d, ref d._PrecioUnitario, sf);
                }
                private static bool _PrecioUnitario_ComputeIsReadOnly(global::LightSwitchApplication.DetalleVenta e)
                {
                    bool result = false;
                    e.PrecioUnitario_IsReadOnly(ref result);
                    return result;
                }
                private static void _PrecioUnitario_Validate(global::LightSwitchApplication.DetalleVenta e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PrecioUnitario_Validate(r);
                }
                private static global::System.Nullable<decimal> _PrecioUnitario_GetImplementationValue(global::LightSwitchApplication.DetalleVenta.DetailsClass d)
                {
                    return d.ImplementationEntity.PrecioUnitario;
                }
                private static void _PrecioUnitario_SetImplementationValue(global::LightSwitchApplication.DetalleVenta.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.PrecioUnitario = v;
                }
                private static void _PrecioUnitario_OnValueChanged(global::LightSwitchApplication.DetalleVenta e)
                {
                    e.PrecioUnitario_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, int>.Entry
                    Cantidad = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, int>.Entry(
                        "Cantidad",
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Cantidad_Stub,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Cantidad_ComputeIsReadOnly,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Cantidad_Validate,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Cantidad_GetImplementationValue,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Cantidad_SetImplementationValue,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Cantidad_OnValueChanged);
                private static void _Cantidad_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DetalleVenta.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, int>.Data> c, global::LightSwitchApplication.DetalleVenta.DetailsClass d, object sf)
                {
                    c(d, ref d._Cantidad, sf);
                }
                private static bool _Cantidad_ComputeIsReadOnly(global::LightSwitchApplication.DetalleVenta e)
                {
                    bool result = false;
                    e.Cantidad_IsReadOnly(ref result);
                    return result;
                }
                private static void _Cantidad_Validate(global::LightSwitchApplication.DetalleVenta e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Cantidad_Validate(r);
                }
                private static int _Cantidad_GetImplementationValue(global::LightSwitchApplication.DetalleVenta.DetailsClass d)
                {
                    return d.ImplementationEntity.Cantidad;
                }
                private static void _Cantidad_SetImplementationValue(global::LightSwitchApplication.DetalleVenta.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Cantidad = v;
                }
                private static void _Cantidad_OnValueChanged(global::LightSwitchApplication.DetalleVenta e)
                {
                    e.Cantidad_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, decimal>.Entry
                    Subtotal = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, decimal>.Entry(
                        "Subtotal",
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Subtotal_Stub,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Subtotal_Validate,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Subtotal_ComputeValue);
                private static void _Subtotal_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DetalleVenta.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.DetalleVenta.DetailsClass d, object sf)
                {
                    c(d, ref d._Subtotal, sf);
                }
                private static void _Subtotal_Validate(global::LightSwitchApplication.DetalleVenta e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Subtotal_Validate(r);
                }
                private static decimal _Subtotal_ComputeValue(global::LightSwitchApplication.DetalleVenta e)
                {
                    decimal value = default(decimal);
                    e.Subtotal_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DetalleVenta.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, int>.Data> c, global::LightSwitchApplication.DetalleVenta.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.DetalleVenta e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.DetalleVenta e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.DetalleVenta.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.DetalleVenta e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::LightSwitchApplication.Producto>.Entry
                    Producto = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::LightSwitchApplication.Producto>.Entry(
                        "Producto",
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Producto_Stub,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Producto_ComputeIsReadOnly,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Producto_Validate,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Producto_GetCoreImplementationValue,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Producto_GetImplementationValue,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Producto_SetImplementationValue,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Producto_Refresh,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._Producto_OnValueChanged);
                private static void _Producto_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DetalleVenta.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::LightSwitchApplication.Producto>.Data> c, global::LightSwitchApplication.DetalleVenta.DetailsClass d, object sf)
                {
                    c(d, ref d._Producto, sf);
                }
                private static bool _Producto_ComputeIsReadOnly(global::LightSwitchApplication.DetalleVenta e)
                {
                    bool result = false;
                    e.Producto_IsReadOnly(ref result);
                    return result;
                }
                private static void _Producto_Validate(global::LightSwitchApplication.DetalleVenta e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Producto_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Producto_GetCoreImplementationValue(global::LightSwitchApplication.DetalleVenta.DetailsClass d)
                {
                    return d.ImplementationEntity.Producto;
                }
                private static global::LightSwitchApplication.Producto _Producto_GetImplementationValue(global::LightSwitchApplication.DetalleVenta.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Producto, global::LightSwitchApplication.Producto.DetailsClass>(global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.Producto, ref d._Producto);
                }
                private static void _Producto_SetImplementationValue(global::LightSwitchApplication.DetalleVenta.DetailsClass d, global::LightSwitchApplication.Producto v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.Producto, ref d._Producto, (i, ev) => i.Producto = ev, v);
                }
                private static void _Producto_Refresh(global::LightSwitchApplication.DetalleVenta.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.Producto, ref d._Producto);
                }
                private static void _Producto_OnValueChanged(global::LightSwitchApplication.DetalleVenta e)
                {
                    e.Producto_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::LightSwitchApplication.VentaSet>.Entry
                    VentaSet = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::LightSwitchApplication.VentaSet>.Entry(
                        "VentaSet",
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._VentaSet_Stub,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._VentaSet_ComputeIsReadOnly,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._VentaSet_Validate,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._VentaSet_GetCoreImplementationValue,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._VentaSet_GetImplementationValue,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._VentaSet_SetImplementationValue,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._VentaSet_Refresh,
                        global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties._VentaSet_OnValueChanged);
                private static void _VentaSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DetalleVenta.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::LightSwitchApplication.VentaSet>.Data> c, global::LightSwitchApplication.DetalleVenta.DetailsClass d, object sf)
                {
                    c(d, ref d._VentaSet, sf);
                }
                private static bool _VentaSet_ComputeIsReadOnly(global::LightSwitchApplication.DetalleVenta e)
                {
                    bool result = false;
                    e.VentaSet_IsReadOnly(ref result);
                    return result;
                }
                private static void _VentaSet_Validate(global::LightSwitchApplication.DetalleVenta e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.VentaSet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _VentaSet_GetCoreImplementationValue(global::LightSwitchApplication.DetalleVenta.DetailsClass d)
                {
                    return d.ImplementationEntity.VentaSet;
                }
                private static global::LightSwitchApplication.VentaSet _VentaSet_GetImplementationValue(global::LightSwitchApplication.DetalleVenta.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass>(global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.VentaSet, ref d._VentaSet);
                }
                private static void _VentaSet_SetImplementationValue(global::LightSwitchApplication.DetalleVenta.DetailsClass d, global::LightSwitchApplication.VentaSet v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.VentaSet, ref d._VentaSet, (i, ev) => i.VentaSet = ev, v);
                }
                private static void _VentaSet_Refresh(global::LightSwitchApplication.DetalleVenta.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.DetalleVenta.DetailsClass.PropertySetProperties.VentaSet, ref d._VentaSet);
                }
                private static void _VentaSet_OnValueChanged(global::LightSwitchApplication.DetalleVenta e)
                {
                    e.VentaSet_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::System.Nullable<decimal>>.Data _PrecioUnitario;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, int>.Data _Cantidad;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, decimal>.Data _Subtotal;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::LightSwitchApplication.Producto>.Data _Producto;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass, global::LightSwitchApplication.VentaSet>.Data _VentaSet;
            
        }
    
        #endregion
    }
    
    #endregion
}
