

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No hay ninguna descripción modelada
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Compra : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Inicializa una nueva instancia de la entidad Compra.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Compra()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Compra(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Compra> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Compra.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Compra_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Compra_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return global::LightSwitchApplication.Compra.DetailsClass.GetValue(this, global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.Fecha);
            }
            set
            {
                global::LightSwitchApplication.Compra.DetailsClass.SetValue(this, global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.Fecha, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Total
        {
            get
            {
                return global::LightSwitchApplication.Compra.DetailsClass.GetValue(this, global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.Total);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Total_Compute(ref decimal result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Total_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Compra.DetailsClass.GetValue(this, global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.DetalleCompra> DetalleCompra
        {
            get
            {
                return global::LightSwitchApplication.Compra.DetailsClass.GetValue(this, global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.DetalleCompra);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.DetalleCompra> DetalleCompraQuery
        {
            get
            {
                return global::LightSwitchApplication.Compra.DetailsClass.GetQuery(this, global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.DetalleCompra);
            }
        }

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Proveedor Proveedor
        {
            get
            {
                return global::LightSwitchApplication.Compra.DetailsClass.GetValue(this, global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.Proveedor);
            }
            set
            {
                global::LightSwitchApplication.Compra.DetailsClass.SetValue(this, global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.Proveedor, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Proveedor_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Proveedor_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Proveedor_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Compra,
                global::LightSwitchApplication.Compra.DetailsClass,
                global::LightSwitchApplication.Compra.DetailsClass.IImplementation,
                global::LightSwitchApplication.Compra.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.Fecha;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass>.Entry
                __CompraEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass>.Entry(
                    global::LightSwitchApplication.Compra.DetailsClass.__Compra_CreateNew,
                    global::LightSwitchApplication.Compra.DetailsClass.__Compra_Created,
                    global::LightSwitchApplication.Compra.DetailsClass.__Compra_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Compra __Compra_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Compra> es)
            {
                return new global::LightSwitchApplication.Compra(es);
            }
            private static void __Compra_Created(global::LightSwitchApplication.Compra e)
            {
                e.Compra_Created();
            }
            private static bool __Compra_AllowSaveWithErrors(global::LightSwitchApplication.Compra e)
            {
                bool result = false;
                e.Compra_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Compra.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::System.DateTime> Fecha
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.Fecha) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, decimal> Total
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.Total) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::LightSwitchApplication.DetalleCompra> DetalleCompra
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.DetalleCompra) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::LightSwitchApplication.DetalleCompra>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::LightSwitchApplication.Proveedor> Proveedor
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.Proveedor) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::LightSwitchApplication.Proveedor>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.DateTime Fecha { get; set; }
                new int Id { get; }
                new global::System.Collections.IEnumerable DetalleCompra { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Proveedor { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::System.DateTime>.Entry
                    Fecha = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::System.DateTime>.Entry(
                        "Fecha",
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Fecha_Stub,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Fecha_ComputeIsReadOnly,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Fecha_Validate,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Fecha_GetImplementationValue,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Fecha_SetImplementationValue,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Fecha_OnValueChanged);
                private static void _Fecha_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Compra.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Compra.DetailsClass d, object sf)
                {
                    c(d, ref d._Fecha, sf);
                }
                private static bool _Fecha_ComputeIsReadOnly(global::LightSwitchApplication.Compra e)
                {
                    bool result = false;
                    e.Fecha_IsReadOnly(ref result);
                    return result;
                }
                private static void _Fecha_Validate(global::LightSwitchApplication.Compra e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Fecha_Validate(r);
                }
                private static global::System.DateTime _Fecha_GetImplementationValue(global::LightSwitchApplication.Compra.DetailsClass d)
                {
                    return d.ImplementationEntity.Fecha;
                }
                private static void _Fecha_SetImplementationValue(global::LightSwitchApplication.Compra.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.Fecha = global::LightSwitchApplication.Compra.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _Fecha_OnValueChanged(global::LightSwitchApplication.Compra e)
                {
                    e.Fecha_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, decimal>.Entry
                    Total = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, decimal>.Entry(
                        "Total",
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Total_Stub,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Total_Validate,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Total_ComputeValue);
                private static void _Total_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Compra.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.Compra.DetailsClass d, object sf)
                {
                    c(d, ref d._Total, sf);
                }
                private static void _Total_Validate(global::LightSwitchApplication.Compra e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Total_Validate(r);
                }
                private static decimal _Total_ComputeValue(global::LightSwitchApplication.Compra e)
                {
                    decimal value = default(decimal);
                    e.Total_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Compra.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, int>.Data> c, global::LightSwitchApplication.Compra.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Compra e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Compra e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Compra.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Compra e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::LightSwitchApplication.DetalleCompra>.Entry
                    DetalleCompra = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::LightSwitchApplication.DetalleCompra>.Entry(
                        "DetalleCompra",
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._DetalleCompra_Stub,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._DetalleCompra_GetReferencedEntities,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._DetalleCompra_GetEntityCollection);
                private static void _DetalleCompra_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Compra.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::LightSwitchApplication.DetalleCompra>.Data> c, global::LightSwitchApplication.Compra.DetailsClass d, object sf)
                {
                    c(d, ref d._DetalleCompra, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.DetalleCompra> _DetalleCompra_GetReferencedEntities(global::LightSwitchApplication.Compra.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.DetalleCompra, global::LightSwitchApplication.DetalleCompra.DetailsClass>(global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.DetalleCompra, ref d._DetalleCompra);
                }
                private static global::System.Collections.IEnumerable _DetalleCompra_GetEntityCollection(global::LightSwitchApplication.Compra.DetailsClass d)
                {
                    return d.ImplementationEntity.DetalleCompra;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::LightSwitchApplication.Proveedor>.Entry
                    Proveedor = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::LightSwitchApplication.Proveedor>.Entry(
                        "Proveedor",
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Proveedor_Stub,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Proveedor_ComputeIsReadOnly,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Proveedor_Validate,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Proveedor_GetCoreImplementationValue,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Proveedor_GetImplementationValue,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Proveedor_SetImplementationValue,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Proveedor_Refresh,
                        global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties._Proveedor_OnValueChanged);
                private static void _Proveedor_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Compra.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::LightSwitchApplication.Proveedor>.Data> c, global::LightSwitchApplication.Compra.DetailsClass d, object sf)
                {
                    c(d, ref d._Proveedor, sf);
                }
                private static bool _Proveedor_ComputeIsReadOnly(global::LightSwitchApplication.Compra e)
                {
                    bool result = false;
                    e.Proveedor_IsReadOnly(ref result);
                    return result;
                }
                private static void _Proveedor_Validate(global::LightSwitchApplication.Compra e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Proveedor_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Proveedor_GetCoreImplementationValue(global::LightSwitchApplication.Compra.DetailsClass d)
                {
                    return d.ImplementationEntity.Proveedor;
                }
                private static global::LightSwitchApplication.Proveedor _Proveedor_GetImplementationValue(global::LightSwitchApplication.Compra.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Proveedor, global::LightSwitchApplication.Proveedor.DetailsClass>(global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.Proveedor, ref d._Proveedor);
                }
                private static void _Proveedor_SetImplementationValue(global::LightSwitchApplication.Compra.DetailsClass d, global::LightSwitchApplication.Proveedor v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.Proveedor, ref d._Proveedor, (i, ev) => i.Proveedor = ev, v);
                }
                private static void _Proveedor_Refresh(global::LightSwitchApplication.Compra.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Compra.DetailsClass.PropertySetProperties.Proveedor, ref d._Proveedor);
                }
                private static void _Proveedor_OnValueChanged(global::LightSwitchApplication.Compra e)
                {
                    e.Proveedor_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::System.DateTime>.Data _Fecha;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, decimal>.Data _Total;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::LightSwitchApplication.DetalleCompra>.Data _DetalleCompra;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Compra, global::LightSwitchApplication.Compra.DetailsClass, global::LightSwitchApplication.Proveedor>.Data _Proveedor;
            
        }
    
        #endregion
    }
    
    #endregion
}
