

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No hay ninguna descripción modelada
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Cliente : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Inicializa una nueva instancia de la entidad Cliente.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Cliente()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Cliente(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Cliente> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Cliente.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cliente_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cliente_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public long DNI
        {
            get
            {
                return global::LightSwitchApplication.Cliente.DetailsClass.GetValue(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.DNI);
            }
            set
            {
                global::LightSwitchApplication.Cliente.DetailsClass.SetValue(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.DNI, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DNI_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DNI_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DNI_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Apellido
        {
            get
            {
                return global::LightSwitchApplication.Cliente.DetailsClass.GetValue(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.Apellido);
            }
            set
            {
                global::LightSwitchApplication.Cliente.DetailsClass.SetValue(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.Apellido, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Apellido_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Apellido_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Apellido_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Nombre
        {
            get
            {
                return global::LightSwitchApplication.Cliente.DetailsClass.GetValue(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.Nombre);
            }
            set
            {
                global::LightSwitchApplication.Cliente.DetailsClass.SetValue(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.Nombre, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nombre_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nombre_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nombre_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public long CUIL
        {
            get
            {
                return global::LightSwitchApplication.Cliente.DetailsClass.GetValue(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.CUIL);
            }
            set
            {
                global::LightSwitchApplication.Cliente.DetailsClass.SetValue(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.CUIL, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CUIL_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CUIL_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CUIL_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Direccion
        {
            get
            {
                return global::LightSwitchApplication.Cliente.DetailsClass.GetValue(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.Direccion);
            }
            set
            {
                global::LightSwitchApplication.Cliente.DetailsClass.SetValue(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.Direccion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Direccion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Direccion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Direccion_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Telefono
        {
            get
            {
                return global::LightSwitchApplication.Cliente.DetailsClass.GetValue(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.Telefono);
            }
            set
            {
                global::LightSwitchApplication.Cliente.DetailsClass.SetValue(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.Telefono, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Telefono_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Telefono_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Telefono_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Cliente.DetailsClass.GetValue(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.VentaSet> VentaSet
        {
            get
            {
                return global::LightSwitchApplication.Cliente.DetailsClass.GetValue(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.VentaSet);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.VentaSet> VentaSetQuery
        {
            get
            {
                return global::LightSwitchApplication.Cliente.DetailsClass.GetQuery(this, global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.VentaSet);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Cliente,
                global::LightSwitchApplication.Cliente.DetailsClass,
                global::LightSwitchApplication.Cliente.DetailsClass.IImplementation,
                global::LightSwitchApplication.Cliente.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.DNI;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass>.Entry
                __ClienteEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass>.Entry(
                    global::LightSwitchApplication.Cliente.DetailsClass.__Cliente_CreateNew,
                    global::LightSwitchApplication.Cliente.DetailsClass.__Cliente_Created,
                    global::LightSwitchApplication.Cliente.DetailsClass.__Cliente_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Cliente __Cliente_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Cliente> es)
            {
                return new global::LightSwitchApplication.Cliente(es);
            }
            private static void __Cliente_Created(global::LightSwitchApplication.Cliente e)
            {
                e.Cliente_Created();
            }
            private static bool __Cliente_AllowSaveWithErrors(global::LightSwitchApplication.Cliente e)
            {
                bool result = false;
                e.Cliente_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Cliente.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, long> DNI
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.DNI) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, long>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string> Apellido
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.Apellido) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string> Nombre
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.Nombre) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, long> CUIL
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.CUIL) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, long>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string> Direccion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.Direccion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string> Telefono
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.Telefono) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, global::LightSwitchApplication.VentaSet> VentaSet
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.VentaSet) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, global::LightSwitchApplication.VentaSet>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new long DNI { get; set; }
                new string Apellido { get; set; }
                new string Nombre { get; set; }
                new long CUIL { get; set; }
                new string Direccion { get; set; }
                new string Telefono { get; set; }
                new int Id { get; }
                new global::System.Collections.IEnumerable VentaSet { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, long>.Entry
                    DNI = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, long>.Entry(
                        "DNI",
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._DNI_Stub,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._DNI_ComputeIsReadOnly,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._DNI_Validate,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._DNI_GetImplementationValue,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._DNI_SetImplementationValue,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._DNI_OnValueChanged);
                private static void _DNI_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Cliente.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, long>.Data> c, global::LightSwitchApplication.Cliente.DetailsClass d, object sf)
                {
                    c(d, ref d._DNI, sf);
                }
                private static bool _DNI_ComputeIsReadOnly(global::LightSwitchApplication.Cliente e)
                {
                    bool result = false;
                    e.DNI_IsReadOnly(ref result);
                    return result;
                }
                private static void _DNI_Validate(global::LightSwitchApplication.Cliente e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DNI_Validate(r);
                }
                private static long _DNI_GetImplementationValue(global::LightSwitchApplication.Cliente.DetailsClass d)
                {
                    return d.ImplementationEntity.DNI;
                }
                private static void _DNI_SetImplementationValue(global::LightSwitchApplication.Cliente.DetailsClass d, long v)
                {
                    d.ImplementationEntity.DNI = v;
                }
                private static void _DNI_OnValueChanged(global::LightSwitchApplication.Cliente e)
                {
                    e.DNI_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Entry
                    Apellido = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Entry(
                        "Apellido",
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Apellido_Stub,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Apellido_ComputeIsReadOnly,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Apellido_Validate,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Apellido_GetImplementationValue,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Apellido_SetImplementationValue,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Apellido_OnValueChanged);
                private static void _Apellido_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Cliente.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Data> c, global::LightSwitchApplication.Cliente.DetailsClass d, object sf)
                {
                    c(d, ref d._Apellido, sf);
                }
                private static bool _Apellido_ComputeIsReadOnly(global::LightSwitchApplication.Cliente e)
                {
                    bool result = false;
                    e.Apellido_IsReadOnly(ref result);
                    return result;
                }
                private static void _Apellido_Validate(global::LightSwitchApplication.Cliente e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Apellido_Validate(r);
                }
                private static string _Apellido_GetImplementationValue(global::LightSwitchApplication.Cliente.DetailsClass d)
                {
                    return d.ImplementationEntity.Apellido;
                }
                private static void _Apellido_SetImplementationValue(global::LightSwitchApplication.Cliente.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Apellido = v;
                }
                private static void _Apellido_OnValueChanged(global::LightSwitchApplication.Cliente e)
                {
                    e.Apellido_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Entry
                    Nombre = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Entry(
                        "Nombre",
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Nombre_Stub,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Nombre_ComputeIsReadOnly,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Nombre_Validate,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Nombre_GetImplementationValue,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Nombre_SetImplementationValue,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Nombre_OnValueChanged);
                private static void _Nombre_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Cliente.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Data> c, global::LightSwitchApplication.Cliente.DetailsClass d, object sf)
                {
                    c(d, ref d._Nombre, sf);
                }
                private static bool _Nombre_ComputeIsReadOnly(global::LightSwitchApplication.Cliente e)
                {
                    bool result = false;
                    e.Nombre_IsReadOnly(ref result);
                    return result;
                }
                private static void _Nombre_Validate(global::LightSwitchApplication.Cliente e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Nombre_Validate(r);
                }
                private static string _Nombre_GetImplementationValue(global::LightSwitchApplication.Cliente.DetailsClass d)
                {
                    return d.ImplementationEntity.Nombre;
                }
                private static void _Nombre_SetImplementationValue(global::LightSwitchApplication.Cliente.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Nombre = v;
                }
                private static void _Nombre_OnValueChanged(global::LightSwitchApplication.Cliente e)
                {
                    e.Nombre_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, long>.Entry
                    CUIL = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, long>.Entry(
                        "CUIL",
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._CUIL_Stub,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._CUIL_ComputeIsReadOnly,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._CUIL_Validate,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._CUIL_GetImplementationValue,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._CUIL_SetImplementationValue,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._CUIL_OnValueChanged);
                private static void _CUIL_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Cliente.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, long>.Data> c, global::LightSwitchApplication.Cliente.DetailsClass d, object sf)
                {
                    c(d, ref d._CUIL, sf);
                }
                private static bool _CUIL_ComputeIsReadOnly(global::LightSwitchApplication.Cliente e)
                {
                    bool result = false;
                    e.CUIL_IsReadOnly(ref result);
                    return result;
                }
                private static void _CUIL_Validate(global::LightSwitchApplication.Cliente e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CUIL_Validate(r);
                }
                private static long _CUIL_GetImplementationValue(global::LightSwitchApplication.Cliente.DetailsClass d)
                {
                    return d.ImplementationEntity.CUIL;
                }
                private static void _CUIL_SetImplementationValue(global::LightSwitchApplication.Cliente.DetailsClass d, long v)
                {
                    d.ImplementationEntity.CUIL = v;
                }
                private static void _CUIL_OnValueChanged(global::LightSwitchApplication.Cliente e)
                {
                    e.CUIL_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Entry
                    Direccion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Entry(
                        "Direccion",
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Direccion_Stub,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Direccion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Direccion_Validate,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Direccion_GetImplementationValue,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Direccion_SetImplementationValue,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Direccion_OnValueChanged);
                private static void _Direccion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Cliente.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Data> c, global::LightSwitchApplication.Cliente.DetailsClass d, object sf)
                {
                    c(d, ref d._Direccion, sf);
                }
                private static bool _Direccion_ComputeIsReadOnly(global::LightSwitchApplication.Cliente e)
                {
                    bool result = false;
                    e.Direccion_IsReadOnly(ref result);
                    return result;
                }
                private static void _Direccion_Validate(global::LightSwitchApplication.Cliente e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Direccion_Validate(r);
                }
                private static string _Direccion_GetImplementationValue(global::LightSwitchApplication.Cliente.DetailsClass d)
                {
                    return d.ImplementationEntity.Direccion;
                }
                private static void _Direccion_SetImplementationValue(global::LightSwitchApplication.Cliente.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Direccion = v;
                }
                private static void _Direccion_OnValueChanged(global::LightSwitchApplication.Cliente e)
                {
                    e.Direccion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Entry
                    Telefono = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Entry(
                        "Telefono",
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Telefono_Stub,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Telefono_ComputeIsReadOnly,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Telefono_Validate,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Telefono_GetImplementationValue,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Telefono_SetImplementationValue,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Telefono_OnValueChanged);
                private static void _Telefono_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Cliente.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Data> c, global::LightSwitchApplication.Cliente.DetailsClass d, object sf)
                {
                    c(d, ref d._Telefono, sf);
                }
                private static bool _Telefono_ComputeIsReadOnly(global::LightSwitchApplication.Cliente e)
                {
                    bool result = false;
                    e.Telefono_IsReadOnly(ref result);
                    return result;
                }
                private static void _Telefono_Validate(global::LightSwitchApplication.Cliente e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Telefono_Validate(r);
                }
                private static string _Telefono_GetImplementationValue(global::LightSwitchApplication.Cliente.DetailsClass d)
                {
                    return d.ImplementationEntity.Telefono;
                }
                private static void _Telefono_SetImplementationValue(global::LightSwitchApplication.Cliente.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Telefono = v;
                }
                private static void _Telefono_OnValueChanged(global::LightSwitchApplication.Cliente e)
                {
                    e.Telefono_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Cliente.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, int>.Data> c, global::LightSwitchApplication.Cliente.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Cliente e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Cliente e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Cliente.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Cliente e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, global::LightSwitchApplication.VentaSet>.Entry
                    VentaSet = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, global::LightSwitchApplication.VentaSet>.Entry(
                        "VentaSet",
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._VentaSet_Stub,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._VentaSet_GetReferencedEntities,
                        global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties._VentaSet_GetEntityCollection);
                private static void _VentaSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Cliente.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, global::LightSwitchApplication.VentaSet>.Data> c, global::LightSwitchApplication.Cliente.DetailsClass d, object sf)
                {
                    c(d, ref d._VentaSet, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.VentaSet> _VentaSet_GetReferencedEntities(global::LightSwitchApplication.Cliente.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass>(global::LightSwitchApplication.Cliente.DetailsClass.PropertySetProperties.VentaSet, ref d._VentaSet);
                }
                private static global::System.Collections.IEnumerable _VentaSet_GetEntityCollection(global::LightSwitchApplication.Cliente.DetailsClass d)
                {
                    return d.ImplementationEntity.VentaSet;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, long>.Data _DNI;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Data _Apellido;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Data _Nombre;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, long>.Data _CUIL;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Data _Direccion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, string>.Data _Telefono;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass, global::LightSwitchApplication.VentaSet>.Data _VentaSet;
            
        }
    
        #endregion
    }
    
    #endregion
}
