

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No hay ninguna descripción modelada
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class VentaSet : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Inicializa una nueva instancia de la entidad VentaSet.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VentaSet()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VentaSet(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.VentaSet> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.VentaSet.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VentaSet_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VentaSet_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return global::LightSwitchApplication.VentaSet.DetailsClass.GetValue(this, global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.Fecha);
            }
            set
            {
                global::LightSwitchApplication.VentaSet.DetailsClass.SetValue(this, global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.Fecha, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Total
        {
            get
            {
                return global::LightSwitchApplication.VentaSet.DetailsClass.GetValue(this, global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.Total);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Total_Compute(ref decimal result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Total_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.VentaSet.DetailsClass.GetValue(this, global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.DetalleVenta> DetalleVenta
        {
            get
            {
                return global::LightSwitchApplication.VentaSet.DetailsClass.GetValue(this, global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.DetalleVenta);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.DetalleVenta> DetalleVentaQuery
        {
            get
            {
                return global::LightSwitchApplication.VentaSet.DetailsClass.GetQuery(this, global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.DetalleVenta);
            }
        }

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Empleado Empleado
        {
            get
            {
                return global::LightSwitchApplication.VentaSet.DetailsClass.GetValue(this, global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.Empleado);
            }
            set
            {
                global::LightSwitchApplication.VentaSet.DetailsClass.SetValue(this, global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.Empleado, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Empleado_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Empleado_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Empleado_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Cliente ClienteSetItem
        {
            get
            {
                return global::LightSwitchApplication.VentaSet.DetailsClass.GetValue(this, global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.ClienteSetItem);
            }
            set
            {
                global::LightSwitchApplication.VentaSet.DetailsClass.SetValue(this, global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.ClienteSetItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClienteSetItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClienteSetItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClienteSetItem_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.VentaSet,
                global::LightSwitchApplication.VentaSet.DetailsClass,
                global::LightSwitchApplication.VentaSet.DetailsClass.IImplementation,
                global::LightSwitchApplication.VentaSet.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.Fecha;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass>.Entry
                __VentaSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass>.Entry(
                    global::LightSwitchApplication.VentaSet.DetailsClass.__VentaSet_CreateNew,
                    global::LightSwitchApplication.VentaSet.DetailsClass.__VentaSet_Created,
                    global::LightSwitchApplication.VentaSet.DetailsClass.__VentaSet_AllowSaveWithErrors);
            private static global::LightSwitchApplication.VentaSet __VentaSet_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.VentaSet> es)
            {
                return new global::LightSwitchApplication.VentaSet(es);
            }
            private static void __VentaSet_Created(global::LightSwitchApplication.VentaSet e)
            {
                e.VentaSet_Created();
            }
            private static bool __VentaSet_AllowSaveWithErrors(global::LightSwitchApplication.VentaSet e)
            {
                bool result = false;
                e.VentaSet_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.VentaSet.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::System.DateTime> Fecha
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.Fecha) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, decimal> Total
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.Total) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.DetalleVenta> DetalleVenta
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.DetalleVenta) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.DetalleVenta>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.Empleado> Empleado
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.Empleado) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.Empleado>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.Cliente> ClienteSetItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.ClienteSetItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.Cliente>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.DateTime Fecha { get; set; }
                new int Id { get; }
                new global::System.Collections.IEnumerable DetalleVenta { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Empleado { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation ClienteSetItem { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::System.DateTime>.Entry
                    Fecha = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::System.DateTime>.Entry(
                        "Fecha",
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Fecha_Stub,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Fecha_ComputeIsReadOnly,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Fecha_Validate,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Fecha_GetImplementationValue,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Fecha_SetImplementationValue,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Fecha_OnValueChanged);
                private static void _Fecha_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VentaSet.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.VentaSet.DetailsClass d, object sf)
                {
                    c(d, ref d._Fecha, sf);
                }
                private static bool _Fecha_ComputeIsReadOnly(global::LightSwitchApplication.VentaSet e)
                {
                    bool result = false;
                    e.Fecha_IsReadOnly(ref result);
                    return result;
                }
                private static void _Fecha_Validate(global::LightSwitchApplication.VentaSet e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Fecha_Validate(r);
                }
                private static global::System.DateTime _Fecha_GetImplementationValue(global::LightSwitchApplication.VentaSet.DetailsClass d)
                {
                    return d.ImplementationEntity.Fecha;
                }
                private static void _Fecha_SetImplementationValue(global::LightSwitchApplication.VentaSet.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.Fecha = global::LightSwitchApplication.VentaSet.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _Fecha_OnValueChanged(global::LightSwitchApplication.VentaSet e)
                {
                    e.Fecha_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, decimal>.Entry
                    Total = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, decimal>.Entry(
                        "Total",
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Total_Stub,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Total_Validate,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Total_ComputeValue);
                private static void _Total_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VentaSet.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.VentaSet.DetailsClass d, object sf)
                {
                    c(d, ref d._Total, sf);
                }
                private static void _Total_Validate(global::LightSwitchApplication.VentaSet e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Total_Validate(r);
                }
                private static decimal _Total_ComputeValue(global::LightSwitchApplication.VentaSet e)
                {
                    decimal value = default(decimal);
                    e.Total_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VentaSet.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, int>.Data> c, global::LightSwitchApplication.VentaSet.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.VentaSet e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.VentaSet e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.VentaSet.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.VentaSet e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.DetalleVenta>.Entry
                    DetalleVenta = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.DetalleVenta>.Entry(
                        "DetalleVenta",
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._DetalleVenta_Stub,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._DetalleVenta_GetReferencedEntities,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._DetalleVenta_GetEntityCollection);
                private static void _DetalleVenta_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VentaSet.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.DetalleVenta>.Data> c, global::LightSwitchApplication.VentaSet.DetailsClass d, object sf)
                {
                    c(d, ref d._DetalleVenta, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.DetalleVenta> _DetalleVenta_GetReferencedEntities(global::LightSwitchApplication.VentaSet.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.DetalleVenta, global::LightSwitchApplication.DetalleVenta.DetailsClass>(global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.DetalleVenta, ref d._DetalleVenta);
                }
                private static global::System.Collections.IEnumerable _DetalleVenta_GetEntityCollection(global::LightSwitchApplication.VentaSet.DetailsClass d)
                {
                    return d.ImplementationEntity.DetalleVenta;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.Empleado>.Entry
                    Empleado = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.Empleado>.Entry(
                        "Empleado",
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Empleado_Stub,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Empleado_ComputeIsReadOnly,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Empleado_Validate,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Empleado_GetCoreImplementationValue,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Empleado_GetImplementationValue,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Empleado_SetImplementationValue,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Empleado_Refresh,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._Empleado_OnValueChanged);
                private static void _Empleado_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VentaSet.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.Empleado>.Data> c, global::LightSwitchApplication.VentaSet.DetailsClass d, object sf)
                {
                    c(d, ref d._Empleado, sf);
                }
                private static bool _Empleado_ComputeIsReadOnly(global::LightSwitchApplication.VentaSet e)
                {
                    bool result = false;
                    e.Empleado_IsReadOnly(ref result);
                    return result;
                }
                private static void _Empleado_Validate(global::LightSwitchApplication.VentaSet e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Empleado_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Empleado_GetCoreImplementationValue(global::LightSwitchApplication.VentaSet.DetailsClass d)
                {
                    return d.ImplementationEntity.Empleado;
                }
                private static global::LightSwitchApplication.Empleado _Empleado_GetImplementationValue(global::LightSwitchApplication.VentaSet.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Empleado, global::LightSwitchApplication.Empleado.DetailsClass>(global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.Empleado, ref d._Empleado);
                }
                private static void _Empleado_SetImplementationValue(global::LightSwitchApplication.VentaSet.DetailsClass d, global::LightSwitchApplication.Empleado v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.Empleado, ref d._Empleado, (i, ev) => i.Empleado = ev, v);
                }
                private static void _Empleado_Refresh(global::LightSwitchApplication.VentaSet.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.Empleado, ref d._Empleado);
                }
                private static void _Empleado_OnValueChanged(global::LightSwitchApplication.VentaSet e)
                {
                    e.Empleado_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.Cliente>.Entry
                    ClienteSetItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.Cliente>.Entry(
                        "ClienteSetItem",
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._ClienteSetItem_Stub,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._ClienteSetItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._ClienteSetItem_Validate,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._ClienteSetItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._ClienteSetItem_GetImplementationValue,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._ClienteSetItem_SetImplementationValue,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._ClienteSetItem_Refresh,
                        global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties._ClienteSetItem_OnValueChanged);
                private static void _ClienteSetItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VentaSet.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.Cliente>.Data> c, global::LightSwitchApplication.VentaSet.DetailsClass d, object sf)
                {
                    c(d, ref d._ClienteSetItem, sf);
                }
                private static bool _ClienteSetItem_ComputeIsReadOnly(global::LightSwitchApplication.VentaSet e)
                {
                    bool result = false;
                    e.ClienteSetItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _ClienteSetItem_Validate(global::LightSwitchApplication.VentaSet e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ClienteSetItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _ClienteSetItem_GetCoreImplementationValue(global::LightSwitchApplication.VentaSet.DetailsClass d)
                {
                    return d.ImplementationEntity.ClienteSetItem;
                }
                private static global::LightSwitchApplication.Cliente _ClienteSetItem_GetImplementationValue(global::LightSwitchApplication.VentaSet.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Cliente, global::LightSwitchApplication.Cliente.DetailsClass>(global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.ClienteSetItem, ref d._ClienteSetItem);
                }
                private static void _ClienteSetItem_SetImplementationValue(global::LightSwitchApplication.VentaSet.DetailsClass d, global::LightSwitchApplication.Cliente v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.ClienteSetItem, ref d._ClienteSetItem, (i, ev) => i.ClienteSetItem = ev, v);
                }
                private static void _ClienteSetItem_Refresh(global::LightSwitchApplication.VentaSet.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.VentaSet.DetailsClass.PropertySetProperties.ClienteSetItem, ref d._ClienteSetItem);
                }
                private static void _ClienteSetItem_OnValueChanged(global::LightSwitchApplication.VentaSet e)
                {
                    e.ClienteSetItem_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::System.DateTime>.Data _Fecha;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, decimal>.Data _Total;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.DetalleVenta>.Data _DetalleVenta;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.Empleado>.Data _Empleado;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VentaSet, global::LightSwitchApplication.VentaSet.DetailsClass, global::LightSwitchApplication.Cliente>.Data _ClienteSetItem;
            
        }
    
        #endregion
    }
    
    #endregion
}
