

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No hay ninguna descripción modelada
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Cargo : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Inicializa una nueva instancia de la entidad Cargo.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Cargo()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Cargo(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Cargo> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Cargo.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cargo_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cargo_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Cargo.DetailsClass.GetValue(this, global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string NombreCargo
        {
            get
            {
                return global::LightSwitchApplication.Cargo.DetailsClass.GetValue(this, global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.NombreCargo);
            }
            set
            {
                global::LightSwitchApplication.Cargo.DetailsClass.SetValue(this, global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.NombreCargo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NombreCargo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NombreCargo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NombreCargo_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Descripcion
        {
            get
            {
                return global::LightSwitchApplication.Cargo.DetailsClass.GetValue(this, global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.Descripcion);
            }
            set
            {
                global::LightSwitchApplication.Cargo.DetailsClass.SetValue(this, global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.Descripcion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Descripcion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Descripcion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Descripcion_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double Sueldo
        {
            get
            {
                return global::LightSwitchApplication.Cargo.DetailsClass.GetValue(this, global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.Sueldo);
            }
            set
            {
                global::LightSwitchApplication.Cargo.DetailsClass.SetValue(this, global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.Sueldo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Sueldo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Sueldo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Sueldo_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Empleado> Empleado
        {
            get
            {
                return global::LightSwitchApplication.Cargo.DetailsClass.GetValue(this, global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.Empleado);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Empleado> EmpleadoQuery
        {
            get
            {
                return global::LightSwitchApplication.Cargo.DetailsClass.GetQuery(this, global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.Empleado);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Cargo,
                global::LightSwitchApplication.Cargo.DetailsClass,
                global::LightSwitchApplication.Cargo.DetailsClass.IImplementation,
                global::LightSwitchApplication.Cargo.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass>.Entry
                __CargoEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass>.Entry(
                    global::LightSwitchApplication.Cargo.DetailsClass.__Cargo_CreateNew,
                    global::LightSwitchApplication.Cargo.DetailsClass.__Cargo_Created,
                    global::LightSwitchApplication.Cargo.DetailsClass.__Cargo_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Cargo __Cargo_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Cargo> es)
            {
                return new global::LightSwitchApplication.Cargo(es);
            }
            private static void __Cargo_Created(global::LightSwitchApplication.Cargo e)
            {
                e.Cargo_Created();
            }
            private static bool __Cargo_AllowSaveWithErrors(global::LightSwitchApplication.Cargo e)
            {
                bool result = false;
                e.Cargo_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Cargo.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, string> NombreCargo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.NombreCargo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, string> Descripcion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.Descripcion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, double> Sueldo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.Sueldo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, global::LightSwitchApplication.Empleado> Empleado
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.Empleado) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, global::LightSwitchApplication.Empleado>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string NombreCargo { get; set; }
                new string Descripcion { get; set; }
                new double Sueldo { get; set; }
                new global::System.Collections.IEnumerable Empleado { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Cargo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, int>.Data> c, global::LightSwitchApplication.Cargo.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Cargo e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Cargo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Cargo.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Cargo e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, string>.Entry
                    NombreCargo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, string>.Entry(
                        "NombreCargo",
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._NombreCargo_Stub,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._NombreCargo_ComputeIsReadOnly,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._NombreCargo_Validate,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._NombreCargo_GetImplementationValue,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._NombreCargo_SetImplementationValue,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._NombreCargo_OnValueChanged);
                private static void _NombreCargo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Cargo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, string>.Data> c, global::LightSwitchApplication.Cargo.DetailsClass d, object sf)
                {
                    c(d, ref d._NombreCargo, sf);
                }
                private static bool _NombreCargo_ComputeIsReadOnly(global::LightSwitchApplication.Cargo e)
                {
                    bool result = false;
                    e.NombreCargo_IsReadOnly(ref result);
                    return result;
                }
                private static void _NombreCargo_Validate(global::LightSwitchApplication.Cargo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.NombreCargo_Validate(r);
                }
                private static string _NombreCargo_GetImplementationValue(global::LightSwitchApplication.Cargo.DetailsClass d)
                {
                    return d.ImplementationEntity.NombreCargo;
                }
                private static void _NombreCargo_SetImplementationValue(global::LightSwitchApplication.Cargo.DetailsClass d, string v)
                {
                    d.ImplementationEntity.NombreCargo = v;
                }
                private static void _NombreCargo_OnValueChanged(global::LightSwitchApplication.Cargo e)
                {
                    e.NombreCargo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, string>.Entry
                    Descripcion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, string>.Entry(
                        "Descripcion",
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Descripcion_Stub,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Descripcion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Descripcion_Validate,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Descripcion_GetImplementationValue,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Descripcion_SetImplementationValue,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Descripcion_OnValueChanged);
                private static void _Descripcion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Cargo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, string>.Data> c, global::LightSwitchApplication.Cargo.DetailsClass d, object sf)
                {
                    c(d, ref d._Descripcion, sf);
                }
                private static bool _Descripcion_ComputeIsReadOnly(global::LightSwitchApplication.Cargo e)
                {
                    bool result = false;
                    e.Descripcion_IsReadOnly(ref result);
                    return result;
                }
                private static void _Descripcion_Validate(global::LightSwitchApplication.Cargo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Descripcion_Validate(r);
                }
                private static string _Descripcion_GetImplementationValue(global::LightSwitchApplication.Cargo.DetailsClass d)
                {
                    return d.ImplementationEntity.Descripcion;
                }
                private static void _Descripcion_SetImplementationValue(global::LightSwitchApplication.Cargo.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Descripcion = v;
                }
                private static void _Descripcion_OnValueChanged(global::LightSwitchApplication.Cargo e)
                {
                    e.Descripcion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, double>.Entry
                    Sueldo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, double>.Entry(
                        "Sueldo",
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Sueldo_Stub,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Sueldo_ComputeIsReadOnly,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Sueldo_Validate,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Sueldo_GetImplementationValue,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Sueldo_SetImplementationValue,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Sueldo_OnValueChanged);
                private static void _Sueldo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Cargo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, double>.Data> c, global::LightSwitchApplication.Cargo.DetailsClass d, object sf)
                {
                    c(d, ref d._Sueldo, sf);
                }
                private static bool _Sueldo_ComputeIsReadOnly(global::LightSwitchApplication.Cargo e)
                {
                    bool result = false;
                    e.Sueldo_IsReadOnly(ref result);
                    return result;
                }
                private static void _Sueldo_Validate(global::LightSwitchApplication.Cargo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Sueldo_Validate(r);
                }
                private static double _Sueldo_GetImplementationValue(global::LightSwitchApplication.Cargo.DetailsClass d)
                {
                    return d.ImplementationEntity.Sueldo;
                }
                private static void _Sueldo_SetImplementationValue(global::LightSwitchApplication.Cargo.DetailsClass d, double v)
                {
                    d.ImplementationEntity.Sueldo = v;
                }
                private static void _Sueldo_OnValueChanged(global::LightSwitchApplication.Cargo e)
                {
                    e.Sueldo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, global::LightSwitchApplication.Empleado>.Entry
                    Empleado = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, global::LightSwitchApplication.Empleado>.Entry(
                        "Empleado",
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Empleado_Stub,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Empleado_GetReferencedEntities,
                        global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties._Empleado_GetEntityCollection);
                private static void _Empleado_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Cargo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, global::LightSwitchApplication.Empleado>.Data> c, global::LightSwitchApplication.Cargo.DetailsClass d, object sf)
                {
                    c(d, ref d._Empleado, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Empleado> _Empleado_GetReferencedEntities(global::LightSwitchApplication.Cargo.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Empleado, global::LightSwitchApplication.Empleado.DetailsClass>(global::LightSwitchApplication.Cargo.DetailsClass.PropertySetProperties.Empleado, ref d._Empleado);
                }
                private static global::System.Collections.IEnumerable _Empleado_GetEntityCollection(global::LightSwitchApplication.Cargo.DetailsClass d)
                {
                    return d.ImplementationEntity.Empleado;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, string>.Data _NombreCargo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, string>.Data _Descripcion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, double>.Data _Sueldo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Cargo, global::LightSwitchApplication.Cargo.DetailsClass, global::LightSwitchApplication.Empleado>.Data _Empleado;
            
        }
    
        #endregion
    }
    
    #endregion
}
